### ISSUE TITLE
cannot "npm install" on windows

### ISSUE THREAD

**Issue by michapixel** [ragulka/sails-starter-app#3]
throws a hell of errors at me ;-)
debug-log:
https://gist.github.com/michapixel/5037069

**Comment by ragulka** [comment]
Hey, I don't have a windows box, so I cannot really comment on what's happening and why. Just use Linux or OSX..  Just kidding. But really, I don't know what's going on and the link you provided seems to point somewhere else, it doesn't look anything like a debug log from npm.

**Comment by ronaldcurtis** [comment]
I had this issue as well at work on a windows box. I simply replaced bcrypt with bcryptjs: https://github.com/dcodeIO/bcrypt.js. Pretty much has the exact same api as the other one, but with no dependencies, and works on all platforms.
