### ISSUE TITLE
How to expose kue UI

### ISSUE THREAD

**Issue by anabelle** [ragulka/sails-starter-app#5]
Hi, do you think is possible to show the KUE UI inside a sails app?
Maybe as a mounted app?

**Comment by kithokit** [comment]
Hi @anabelle, Are you able to show the KUE UI inside a sails app now? I still can't find the solution

**Comment by anabelle** [comment]
Hi @kithokit I managed to do it by mounting it in a different port:

https://github.com/8manos/colaborativo.js/blob/master/api/services/JobsKue.js#L29

**Comment by anabelle** [comment]
You can see it working here: http://beta.colaborativo.co/kue/active

**Comment by anabelle** [comment]
This custom middleware setting is also relevant: https://github.com/8manos/colaborativo.js/blob/master/config/express.js#L78

**Comment by kithokit** [comment]
Hi anabelle, afaik, the config/express.js is deprecated in Sails.js v10

**Comment by kithokit** [comment]
in V10, we use config/http.js 

module.exports.http = {
    customMiddleware: function (app) {

```
    var kue = require('kue');
    app.use('/tools/queue', kue.app);
 }
```

}

**Comment by tobalsgithub** [comment]
BTW, I keep seeing this example posted in different places. For me, 
 `app.use('/tools/queue', kue.app);`
does not work. But
 `app.use('/tools/queue/', kue.app); // note the trailing slash`
works perfect.
