### ISSUE TITLE
Can't sails lift -- smtp undefined in Mailer.js

### ISSUE THREAD

**Issue by alexlenail** [ragulka/sails-starter-app#8]
/Users/alenail/Documents/bluemoon/sails-starter-app/api/services/Mailer.js:12
  host: sails.config.smtp.host,
                         ^
TypeError: Cannot read property 'host' of undefined

What do you make of this? I cloned, npm installed, started mongo, and tried to sails lift.

**Comment by msimonc** [comment]
In config/mail.js try adding:
module.exports.smtp = {
    host: '',
    ssl: '',
    port: '',
    user: '',
    pass: ''
};
(add your smtp values as required)

**Comment by alexlenail** [comment]
Thanks! That seems to have worked, or at least putting arbitrary data in allowed me to 'lift'. Could you point me to an article that explains what these values need to be? My initial googling hasn't given me any excellent results, especially because I'm not sure exactly what I'm looking for.

**Comment by ragulka** [comment]
These are the settings for Nodemailer. You can find out more about it here: https://github.com/andris9/Nodemailer
